// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jznfnnlxkgshnsjmrljb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6bmZubmx4a2dzaG5zam1ybGpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwOTU1OTksImV4cCI6MjA2MDY3MTU5OX0.MCbNSHkAm6LHZM4jZsWo38dk3OdTpmnneTDtTiQ3dBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);